services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $centrifugoSecret: '%env(CENTRIFUGO_SECRET)%'
            $centrifugoApiEndpoint: '%env(CENTRIFUGO_API_ENDPOINT)%'
            $centrifugoApiKey: '%env(CENTRIFUGO_API_KEY)%'

    Fresh\CentrifugoBundle\Service\:
        resource: '../../Service/'
